GET http://localhost:8989/user
id: 6
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsIm5hbWUiOiJQaXBpc2thIn0.YHlQx7haAPsPhOdd0w8AhFzEaoIte0mYAMlCpd9nVA4


###

POST http://localhost:8989/user
content-type: application/json

{
    "name": "user 6"
}

###

PUT http://localhost:8989/user
content-type: application/json

{
    "id": 2,
    "description": "test todo number 2 was updated"
}

###

DELETE http://localhost:8989/user
content-type: application/json

{
    "id": 3
}