GET http://localhost:8989/user
id: 6


###

POST http://localhost:8989/user
content-type: application/json

{
    "name": "user 6"
}

###

PUT http://localhost:8989/user
content-type: application/json

{
    "id": 2,
    "description": "test todo number 2 was updated"
}

###

DELETE http://localhost:8989/user
content-type: application/json

{
    "id": 3
}